#!/bin/bash

#DEBHELPER#

# postrm script for init-diversity-tools

set -e

case "$1" in
  purge|remove) \
    
    ## Removing diversions
	for F in \
        /etc/init.d/rc    \
        /etc/init.d/rcS
    do
    	if [ -e "$F.dpkg-dist" ]; then
    		rm $F
    	fi
        dpkg-divert --quiet --package init-diversity-tools --rename \
                    --divert /usr/share/init-diversity-tools/diversions$F --remove $F || :
    done
    
    for G in \
        /usr/sbin/shutdown    \
        /usr/sbin/reboot    \
        /usr/sbin/poweroff    \
        /usr/sbin/runlevel
    do
    	if [ -e "$G.dpkg-dist" ]; then
    		rm $G
    	fi
        dpkg-divert --quiet --package init-diversity-tools --rename \
                    --divert /usr/share/init-diversity-tools/diversions$G --remove $G || :
    done


#if polkit setuid override exists, remove it & restore default permissions
if [ -n "$(dpkg-statoverride --list /usr/lib/polkit-1/polkit-agent-helper-1 2>/dev/null)" ]; then
        dpkg-statoverride --remove /usr/lib/polkit-1/polkit-agent-helper-1
        chmod u-s /usr/lib/polkit-1/polkit-agent-helper-1
fi
  ;;
  
  *) :
  ;;

esac

exit 0
